from typing import Protocol, List, Optional, Dict, Any, Tuple
from datetime import date
from app.domain.entities import FuncionarioCobranca, Substituicao, AuditoriaTroca, FinanciamentoRural, InstituicaoPA

class ICobrancaRepository(Protocol):
    def get_by_id(self, cobranca_id: int) -> Optional[FuncionarioCobranca]: ...
    def create(self, entity: FuncionarioCobranca) -> FuncionarioCobranca: ...
    def create_batch(self, entities: List[FuncionarioCobranca]) -> List[FuncionarioCobranca]: ...
    def update(self, entity: FuncionarioCobranca) -> FuncionarioCobranca: ...
    def update_status(self, cobranca_id: int, new_status: int) -> Optional[FuncionarioCobranca]: ...
    def delete(self, cobranca_id: int) -> bool: ...
    def list_paginated(
        self,
        page: Optional[int],
        per_page: Optional[int],
        search: Optional[str],
        time_cobranca: Optional[str],
        pa: Optional[int],
        status: Optional[int],
        substituicao: Optional[str],
        sort_by: str,
        sort_order: str
    ) -> Tuple[List[Dict[str, Any]], int]: ...
    def list_pas(self) -> List[InstituicaoPA]: ...
    def search_funcionarios(self, query: Optional[str]) -> List[Dict[str, Any]]: ...
    def get_analytics_stats(self) -> Dict[str, Any]: ...
    def list_filas_sem_cobradores(self) -> List[Dict[str, Any]]: ...
    def bulk_update(self, ids: List[int], updates: Dict[str, Any]) -> int: ...
    def troca_massa(
        self,
        modo: str,
        novo_cobrador: str,
        nova_matricula: int,
        inativar_origem: bool,
        time: Optional[str] = None,
        num_pa: Optional[int] = None,
        cobrador_origem_id: Optional[int] = None
    ) -> Dict[str, Any]: ...

class ISubstituicaoRepository(Protocol):
    def get_by_id(self, id: int) -> Optional[Substituicao]: ...
    def create(self, entity: Substituicao) -> Substituicao: ...
    def update_dates(self, id: int, data_inicio: date, data_fim: date) -> Optional[Substituicao]: ...
    def cancel(self, id: int) -> bool: ...
    def list_escala(self) -> List[Dict[str, Any]]: ...
    def process_scheduled_substitutions(self) -> Dict[str, int]: ...
    def create_substituicao_massa(
        self,
        modo: str,
        substituto_id: int,
        data_inicio: date,
        data_fim: date,
        time: Optional[str] = None,
        num_pa: Optional[int] = None,
        cobrador_origem_id: Optional[int] = None
    ) -> Dict[str, Any]: ...

class IAuditoriaRepository(Protocol):
    def log(self, entity: AuditoriaTroca) -> AuditoriaTroca: ...
    def list_historico(self, limit: int = 100) -> List[Dict[str, Any]]: ...

class IFinanciamentoRepository(Protocol):
    def get_by_id(self, id: int) -> Optional[FinanciamentoRural]: ...
    def list_all(self) -> List[FinanciamentoRural]: ...
    def create(self, entity: FinanciamentoRural) -> FinanciamentoRural: ...
    def update(self, entity: FinanciamentoRural) -> Optional[FinanciamentoRural]: ...
    def update_status(self, id: int, status: int) -> Optional[FinanciamentoRural]: ...
    def delete(self, id: int) -> bool: ...
    def sync_data_rows(self, rows: List[Tuple[str, str, str, str]]) -> Dict[str, Any]: ...
